### ISSUE TITLE
Multiple Patches

### ISSUE THREAD

**Issue by FourOne** [dreadflopp/dreads_modlist_patches#19]
I noticed some things while finishing your guide and checked if they are covered by your modlist_patches, all of the following are not.

Bells of Skyrim - JKs Sykrim Patch
Keld-Nar - Clockwork Patch
Majestic Mountains - Pilgrims Delight Patch
Survival Mode Patch Collection (Cloaks Of Skyrim & Winter Is Coming)
Even better Quest Objectives - Cutting Room Floor Patch (CRF is installed later so its not automatically chosen in the installer)

I checked all of these in xEdit, but im not 100% sure if they are needed.

**Comment by dreadflopp** [comment]
I will check all these tomorrow. If you've got the time, could you post links to the patches?

**Comment by FourOne** [comment]
[Bells of Skyrim - JKs Sykrim Patch](https://www.nexusmods.com/skyrimspecialedition/mods/10495?tab=files)
[Keld-Nar - Clockwork Patch](https://www.nexusmods.com/skyrimspecialedition/mods/14353?tab=files)
[Majestic Mountains - Pilgrims Delight Patch](https://www.nexusmods.com/skyrimspecialedition/mods/35107?tab=files)
[Survival Mode Patch Collection](https://www.nexusmods.com/skyrimspecialedition/mods/19154?tab=files) (Cloaks Of Skyrim & Winter Is Coming)
[Even better Quest Objectives - Cutting Room Floor Patch](https://www.nexusmods.com/skyrimspecialedition/mods/159?tab=files) (CRF is installed later so its not automatically chosen in the installer)

Since i had them all in my Temp folder for testing i uploaded them.
https://drive.google.com/file/d/1TIIlXv8h4pDCzypb0v0_qjkPOIiJm-cC/view?usp=sharing

**Comment by dreadflopp** [comment]
**Bells of Skyrim - JKs Sykrim Patch**
Added instructions to install the patch

**Keld-Nar - Clockwork Patch**
Added instructions to install the patch

**Majestic Mountains - Pilgrims Delight Patch**
I think this is for the old verssion of MM

**Survival Mode Patch Collection**
Good patches. They don't have an esl-tag so I'll add them to my patches instead since they have open permissions.

**Even better Quest Objectives - Cutting Room Floor Patch**
Moved Cutting Room Floor to fix this
