### ISSUE TITLE
Convenient Carriages

### ISSUE THREAD

**Issue by FourOne** [dreadflopp/dreads_modlist_patches#24]
It seems like some markers are just changed via xEdit, at least on the z axis. Not 100% a bug, but this mod adds/moves rly weird markers. For example the driver in front of Lakeview Manor is mining up in the air... The same driver can use the House when its build, but the mod author also placed a table almost right at the front door (which looks rly out of place).

Other thing i noticed, i toggled the guards via mcm, but this is not working 100%. Somtimes i had to toggle/untoggle again to make them disapear.

I switched back to the old mod, but of course it would be possible to make a fix for most of this.

**Comment by dreadflopp** [comment]
Really, I haven't noticed this but haven't visited that many towns. Noticed some ground clipping in Dawnstar, I think it's the JK's and Arthmoors Villages patches from CC that doesn't fully work together. I fixed the clipping in Dawnstar with a patch. I tried CC because I wanted to try the Greater Cities series and CC has patches for that. If it doesn't work I'll switch back to CFTO in the guide.
